server:
  port: 8083
jwt:
  secret: my-super-secret-key

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: 1821119
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  config: 
    import:
      optional: 
          configserver: http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      productServiceCircuitBreaker:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      paymentDetailsCircuitBreaker:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  timelimiter:
    instances:
      paymentServiceCircuitBreaker:
        timeoutDuration: 3s
      productServiceCircuitBreaker:
        timeoutDuration: 3s
      paymentDetailsCircuitBreaker:
        timeoutDuration: 3s
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
