server:
  port: 8082
#jwt:
  #secret: 3f8e2b9c7d4a6e1f9b0c8d7e6a5f4c3b2a1d0e9f8c7b6a5d4c3b2a1f0e9d8c7b

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: 1821119
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  config: 
    import:
      optional: 
          configserver: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
