server:
  port: 8082
jwt:
  secret: my-super-secret-key

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: 1821119
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  config: 
    import:
      optional: 
          configserver: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
